### ISSUE TITLE
When loading a page, it fails with an exception

### ISSUE THREAD

**Issue by injeniero** [inspectdev/inspect-issues#99]
- Inspect version: 0.7.4
- Electron: 13.1.1
- OS version and architecture: darwin x64 20.6.0
- Language: undefined

Steps to Reproduce:

1.
2.

Uncaught Exception:
Error: maxObjectCount exceeded
at Object.parseBuffer (/Applications/Inspect.app/Contents/Resources/app.asar/node_modules/bplist-parser/bplistParser.js:83:11)
at parseBinaryPlist (/Applications/Inspect.app/Contents/Resources/app.asar/node_modules/appium-support/lib/plist.js:106:22)
at Object.parsePlist (/Applications/Inspect.app/Contents/Resources/app.asar/node_modules/appium-support/lib/plist.js:158:12)
at WebInspectorDecoder._decode (/Applications/Inspect.app/Contents/Resources/app.asar/node_modules/appium-ios-device/lib/webinspector/transformer/webinspector-decoder.js:21:26)
at WebInspectorDecoder._transform (/Applications/Inspect.app/Contents/Resources/app.asar/node_modules/appium-ios-device/lib/webinspector/transformer/webinspector-decoder.js:13:10)
at WebInspectorDecoder.Transform._read (internal/streams/transform.js:205:10)
at WebInspectorDecoder.Transform._write (internal/streams/transform.js:193:12)
at writeOrBuffer (internal/streams/writable.js:358:12)
at WebInspectorDecoder.Writable.write (internal/streams/writable.js:303:10)
at PlistServiceDecoder.ondata (internal/streams/readable.js:719:22)
at PlistServiceDecoder.emit (events.js:315:20)
at addChunk (internal/streams/readable.js:309:12)
at readableAddChunk (internal/streams/readable.js:284:9)
at PlistServiceDecoder.Readable.push (internal/streams/readable.js:223:10)
at PlistServiceDecoder.push (internal/streams/transform.js:166:32)
at PlistServiceDecoder._decode (/Applications/Inspect.app/Contents/Resources/app.asar/node_modules/appium-ios-device/lib/plist-service/transformer/plist-service-decoder.js:27:10)

**Comment by auchenberg** [comment]
@injeniero Can you provide the page you were trying to load?

**Comment by tgv604** [comment]
Getting the same on a busy page (a Shopify storefront with a handful of active apps and widgets)
Windows 11, Inspect 0.7.5, iPad 4 (iOS10.3.4)

![image](https://user-images.githubusercontent.com/8357694/146848557-3b56ada5-f388-4913-b23a-72f43fd5ed58.png)

**Comment by auchenberg** [comment]
@injeniero I tried fixing this, please try to use the new available build of Inspect.
